2018-01-30 05:40:27,582 [Thread-9:140498960951040] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-01-30 06:06:55,159 [b'uWSGIWorker1Core0':140546223937280] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-01-30 06:19:45,395 [b'uWSGIWorker1Core0':139929954678528] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-01-30 06:19:48,892 [b'uWSGIWorker1Core0':139929954678528] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-01-30 06:33:21,668 [b'uWSGIWorker2Core0':139876655769344] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./chatroom/views.py", line 69, in echo
    print(os.getpid())
NameError: name 'os' is not defined
2018-01-30 06:37:03,116 [b'uWSGIWorker1Core0':139886181701376] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /lytest/hlsroom/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./chatroom/views.py", line 36, in index
    logger.debug('****************i'+os.getpid()+'*******************')
NameError: name 'logger' is not defined
2018-01-30 06:37:42,313 [b'uWSGIWorker1Core0':139886181701376] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /lytest/hlsroom/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./chatroom/views.py", line 36, in index
    logger = logging.getLogger('django')
NameError: name 'logger' is not defined
2018-01-30 06:37:50,978 [b'uWSGIWorker1Core0':140592827090688] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /lytest/hlsroom/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./chatroom/views.py", line 37, in index
    logger.debug('****************i'+os.getpid()+'*******************')
NameError: name 'os' is not defined
2018-01-30 06:38:09,425 [b'uWSGIWorker1Core0':140592827090688] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /lytest/hlsroom/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./chatroom/views.py", line 37, in index
    logger = logging.getLogger('django')
NameError: name 'os' is not defined
2018-01-30 06:38:10,844 [b'uWSGIWorker1Core0':140592827090688] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /lytest/hlsroom/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./chatroom/views.py", line 37, in index
    logger = logging.getLogger('django')
NameError: name 'os' is not defined
2018-01-30 06:38:20,201 [b'uWSGIWorker1Core0':139944954574592] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /lytest/hlsroom/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./chatroom/views.py", line 38, in index
    logger.debug('****************i'+os.getpid()+'*******************')
TypeError: Can't convert 'int' object to str implicitly
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.5/dist-packages/django/core/urlresolvers.py", line 374, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./test_chatroom/urls.py", line 20, in <module>
    from Django.views.generic.base import RedirectView
ImportError: No module named 'Django'
Not Found: /static/js/jquery.min.js
Not Found: /static/js/jquery.min.js
Not Found: /static/js/jquery.min.js
Not Found: /static/js/jquery.min.js
Not Found: /static/favicon.ico
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 141, in _wrapped_view
    result = middleware.process_request(request)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/middleware.py", line 25, in process_request
    importlib.import_module(WEBSOCKET_FACTORY_CLASS[:offset]),
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/backends/uwsgi/factory.py", line 1, in <module>
    import uwsgi
ImportError: No module named 'uwsgi'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 67, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 67, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 67, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 67, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/sjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/sjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())++' : '+threading.currentThread()+' : connect*******************')
TypeError: bad operand type for unary +: 'str'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 68, in echo
    logger.debug('****************'+str(os.getpid())+' : '+threading.currentThread()+' : connect*******************')
TypeError: Can't convert 'Thread' object to str implicitly
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 73, in echo
    client.writeback(request.websocket)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 34, in writeback
    logger.debug('****************'+str(os.getpid())+' : '+threading.currentThread()+' : ready to start a new thread*******************')
NameError: name 'logger' is not defined
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 74, in echo
    client.writeback(request.websocket)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 34, in writeback
    logger.debug('****************'+str(os.getpid())+' : '+threading.currentThread()+' : ready to start a new thread*******************')
NameError: name 'logger' is not defined
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 74, in echo
    client.writeback(request.websocket)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 34, in writeback
    logger.debug('****************'+str(os.getpid())+' : '+threading.currentThread()+' : ready to start a new thread*******************')
NameError: name 'logger' is not defined
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 71, in echo
    client.writeback(request.websocket)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 34, in writeback
    logger.debug('****************'+str(os.getpid())+' : '+str(threading.currentThread())+' : ready to start a new thread*******************')
NameError: name 'logger' is not defined
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 72, in echo
    client.writeback(request.websocket)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 35, in writeback
    logger.debug('****************'+str(os.getpid())+' : '+str(threading.currentThread())+' : ready to start a new thread*******************')
NameError: name 'logger' is not defined
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 73, in echo
    client.writeback(request.websocket)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 35, in writeback
    logger.debug('****************'+str(os.getpid())+' : '+str(threading.currentThread())+' : ready to start a new thread*******************')
NameError: name 'logger' is not defined
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 73, in echo
    client.writeback(request.websocket)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 35, in writeback
    logger.debug('****************'+str(os.getpid())+' : '+str(threading.currentThread())+' : ready to start a new thread*******************')
NameError: name 'logger' is not defined
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 73, in echo
    client.writeback(request.websocket)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 35, in writeback
    logger.debug('****************'+str(os.getpid())+' : '+str(threading.currentThread())+' : ready to start a new thread*******************')
NameError: name 'logger' is not defined
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 166, in _wrapped_view
    return middleware.process_response(request, response)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/middleware.py", line 56, in process_response
    request.websocket.close()
AttributeError: 'NoneType' object has no attribute 'close'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print("-->"+str(m))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print("-->"+str(m))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print("-->"+str(m))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print("-->"+str(m))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print("-->"+str(m))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print("-->"+str(m))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print(str(i))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print(str(i))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 77, in echo
    print(str(i))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 166, in _wrapped_view
    return middleware.process_response(request, response)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/middleware.py", line 56, in process_response
    request.websocket.close()
AttributeError: 'NoneType' object has no attribute 'close'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 166, in _wrapped_view
    return middleware.process_response(request, response)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/middleware.py", line 56, in process_response
    request.websocket.close()
AttributeError: 'NoneType' object has no attribute 'close'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 166, in _wrapped_view
    return middleware.process_response(request, response)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/middleware.py", line 56, in process_response
    request.websocket.close()
AttributeError: 'NoneType' object has no attribute 'close'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 166, in _wrapped_view
    return middleware.process_response(request, response)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/middleware.py", line 56, in process_response
    request.websocket.close()
AttributeError: 'NoneType' object has no attribute 'close'
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 86, in echo
    print(str(m))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Internal Server Error: /lytest/hlsroom/echo/xjtu/software/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/loading_21th/dwebsocket/examples/src/dwebsocket-master/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/home/loading_21th/test_chatroom/chatroom/views.py", line 86, in echo
    print(str(m))
  File "/usr/lib/python3.5/threading.py", line 817, in __repr__
    self.is_alive() # easy way to get ._is_stopped set when appropriate
  File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
    self._wait_for_tstate_lock(False)
  File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
    assert self._is_stopped
AssertionError
Not Found: /static/js/jquery.min.js
Not Found: /static/js/jquery.min.js
Not Found: /static/js/jquery.min.js
Not Found: /static/js/jquery.min.js
Not Found: /static/js/jquery.min.js
Not Found: /static/js/jquery.min.js
Not Found: /static/favicon.ico
Not Found: /static/js/jquery.min.js
Not Found: /static/favicon.ico
